### ISSUE TITLE
Add datetime processor

### ISSUE THREAD

**Issue by ikalnytskyi** [ikalnytskyi/holocron#207]
Holocron used to extract "published" datetime out of document path. However, we don't want to maintain this *hardcoded* behavior. One should be able to provide `published`, `created` and `updated` attributes via some third parties (e.g. YAML frontmetter), hence we will need a way to convert these attributes from `str` to `datetime` instanced.

This ticket suggests to implement some datetime processor (the name to be discussed) that will receive a list of attributes to convert, and datetime format string to be used.

Example:

```yaml
processors:
  - name: datetime
    attributes:
      - updated
      - published
    format: '%Y-%m-%d'
```
